### ISSUE TITLE
Error when building windows dll

### ISSUE THREAD

**Issue by yhwang** [yhwang/node#1]
By using the branch here: https://github.com/yhwang/node/tree/add-node-lib , I can build node static lib and use the static lib to build node executable. But when I build the shared lib(dll), it fails in building the node.exe.

And these are the error messages:
```
1>------ Build started: Project: node, Configuration: Release x64 ------
1>   Creating library C:\Users\IBM_ADMIN\node\Release\node.lib and object C:\Users\IBM_ADMIN\node\Release\node.exp
1>Generating code
1>Finished generating code
1>C:\Users\IBM_ADMIN\node\Release\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x3CA06E
1>Done building project "node.vcxproj" -- FAILED.
```

**Comment by yhwang** [comment]
@refack can you chime in this. I will try to provide more information if you need.

**Comment by yhwang** [comment]
I do see the `node.dll`. but it fails in building the `node.exe`. How do I verify the node.dll?

**Comment by refack** [comment]
Ohh sorry, I wasn't around in december.
Did you solve this?

**Comment by yhwang** [comment]
Hi @refack yes, I think. we chatted on whatsapp for this if I remember it correctly. since it's almost one year ago. I believe we solved this issue. Thanks.

I just tried to screen through some old issues and close them. nothing to be worried. Thanks again
